export const routePaths = {
  root: '/',
  login: '/login',
  app: '/app',
  adminDashboard: '/app/admin/dashboard',
  adminEmployees: '/app/admin/employees',
  adminStudents: '/app/admin/students',
  adminActivities: '/app/admin/activities',
  adminSchedules: '/app/admin/schedules',
  adminValidations: '/app/admin/validations',
  adminAttendance: '/app/admin/attendance',
  adminPayroll: '/app/admin/payroll',
  employeeDashboard: '/app/employee/dashboard',
  employeeSchedule: '/app/employee/schedule',
  employeeAttendance: '/app/employee/attendance',
  employeeValidations: '/app/employee/validations',
  employeePayroll: '/app/employee/payroll',
} as const;
